<script lang="ts">
    import { postArtist } from '@src/api/APIAdapter';  // Assuming you have a `postArtist` function
    import { Artista } from '@src/models/ArtistaClass'; // The Artista class
    import { User } from '@src/models/UserClass'; // User class to handle authentication
    import { onMount } from 'svelte';

    // Props and state variables
    export let artistName = '';
    let name = '';
    let fotoUrl = '';
    let albums: string[] = [];  // Assuming albums are represented by an array of IDs or titles

    let message = '';
    let messageColor = 'red';

    let token: string | null;
    let user: User | null;

    // On mount, retrieve token and user from localStorage
    onMount(() => {
        token = localStorage.getItem('token');
        user = User.fromObject(JSON.parse(localStorage.getItem('user') || ''));
    });

    // Handle adding artist
    async function handleAddArtist(event: Event) {
        event.preventDefault();

        // Create an Artista object
        const artist = new Artista(
            '', // ID will be generated by the backend
            name,
            albums,
            fotoUrl || 'https://via.placeholder.com/150'
        );

        try {
            // Send the artist object to your backend using the postArtist function
            const success = await postArtist(artist, token ?? '', user?.admin_secret ?? '', user?.id ?? '');

            if (success) {
                messageColor = 'green';
                message = 'Artista agregado correctamente';
                setTimeout(() => {
                    window.location.href = '/'; // Redirect after success
                }, 1000);
            } else {
                messageColor = 'red';
                message = 'Error interno del servidor, intenta de nuevo';
            }
        } catch (error) {
            console.error('Error al agregar el artista:', error);
            message = 'Ocurrió un error durante el proceso';
        }
    }
</script>

<form on:submit={handleAddArtist}>
    <h2>Agregar Artista</h2>
  
    <label for="name">Nombre del Artista:</label>
    <input type="text" id="name" bind:value={name} class="text-input" required />

    <label for="foto-url">URL de la Foto:</label>
    <input type="text" id="foto-url" bind:value={fotoUrl} class="text-input" />

    {#if message}
        <p class="{messageColor}">{message}</p>
    {/if}
  
    <div class="wrapper">
        <input class="submit" type="submit" value="Agregar Artista" />
    </div>
</form>

<style>
    @import './addartista.css';
</style>
